
finally IO exception 1 thrown without being caught..
throwing IO exception 1..
throwing IO exception 2..
catch exception: intentional IO exception 2..
java.io.IOException: intentional IO exception 2..
	at IOUtil.copyWithStream(IOUtil.java:51)
	at IOUtil.main(IOUtil.java:134)
closing output stream still..
java.io.IOException: intentional IO exception 1..
	at IOUtil.copyWithStream(IOUtil.java:45)
	at IOUtil.main(IOUtil.java:134)
14
4
17
Unable to create: copiedDir: java.nio.file.DirectoryNotEmptyException: copiedDir

-----new test-----
3
15
5
14

-----new test-----
2
16
6
20

-----new test-----
3
14
4
18

-----new test-----
3
14
8
20

-----new test-----
2
18
7
16

-----new test-----
5
17
4
18

-----new test-----
2
16
4
16

-----new test-----
2
11
7
15

-----new test-----
2
17
7
17

-----new test-----
2
18
8
16

-----new test-----
3
20
6
21

-----new test-----
2
15
5
18

-----new test-----
1
15
6
17

-----new test-----
7
4
4
23
